name: C++ Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake libgtest-dev

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ./test/PizzeriaTest
